### ISSUE TITLE
US Census Predictions

### ISSUE THREAD

**Issue by N8sGit** [N8sGit/ai_project_group_8#12]
Question:
Geographic distribution of ML jobs ? Where are the jobs being concentrated ? Onsite/Remote/Hybrid?

Exploratory Analysis:
-

**Comment by MxOdele** [comment]
Switching to US Census predictions.

Question:
Are there any trends and/or correlations across the country or in states with heavier ML investment/jobs in terms of employment, employees in "tech" fields, and/or education levels?

Exploratory Analysis:
- Calculating and predicting trends in population, employment status, employment status in "tech" fields, and levels of education
- .mean(), .sum(), m.predict()
- Line graphs

**Comment by MxOdele** [comment]
Analysis completed

Local files pushed to Gitr
