### ISSUE TITLE
Brainstorm project idea

### ISSUE THREAD

**Issue by N8sGit** [N8sGit/ai_project_group_8#7]
--  Weather/traffic/accident correlations 
     * Air quality
     * 
--  Growth of ML industry/jobs/companies(??)/population usage/public sentiment about AI
     * geographic relationships 
     * salaries 
     * Number of jobs 
     * Job descriptions 
     * Experience levels ? Degree demands / education levels / generational??? 
(Concern with this idea: can we find usable data? Discovery...) 
-- Education + AI 
    * Is AI democratizing ? Availability / access 
    * 
Find  apis, question formulation, data sets, feasibility analysis, etc

**Comment by N8sGit** [comment]
https://coresignal.com/ I'm hoping this API would be all we need for job related stuff

Update: So the APIs offered by this service are super high quality but are geared to businesses. It's EXPENSIVE . Unless I can find some way to use it cheaply I'm ruling it out.

**Comment by N8sGit** [comment]
Another one https://www.statista.com/api

**Comment by N8sGit** [comment]
Another promising one https://rapidapi.com/category/Jobs

**Comment by MxOdele** [comment]
Working on pulling data from: https://www.census.gov/data/developers/data-sets/acs-1year.html
