### ISSUE TITLE
Consolidate datasets

### ISSUE THREAD

**Issue by N8sGit** [N8sGit/ai_project_group_8#8]
Put all data we find from everywhere in one place (links, csvs, etc)

**Comment by FundaSubasi** [comment]
[AI_AmericanCompaniesProfits.csv](https://github.com/N8sGit/ai_project_group_8/files/15242339/AI_AmericanCompaniesProfits.csv)

**Comment by petagaye143** [comment]
[herd_2020.csv.zip](https://github.com/N8sGit/ai_project_group_8/files/15242493/herd_2020.csv.zip)

Variable/Header Key: https://ncsesdata.nsf.gov/explorer/variables?page=1

R&D expenditure by field of research and source of funds and also gathers information on types of research, expenses, and R&D personnel

**Comment by petagaye143** [comment]
[herd_2021.csv (1).zip](https://github.com/N8sGit/ai_project_group_8/files/15242497/herd_2021.csv.1.zip)

Variable/Header Key: https://ncsesdata.nsf.gov/explorer/variables?page=1

R&D expenditure by field of research and source of funds and also gathers information on types of research, expenses, and R&D personnel.

**Comment by N8sGit** [comment]
Here are software developer jobs posted on linkedin in 2023. Ideally I'd find another data set for a previous year(s) to contrast it with. 



[linkedin_postings.csv.zip](https://github.com/N8sGit/ai_project_group_8/files/15242507/linkedin_postings.csv.zip)

**Comment by N8sGit** [comment]
Here's approximately 200 machine learning engineer job listings .

[ml_engineer_jpbs.json.zip](https://github.com/N8sGit/ai_project_group_8/files/15242534/ml_engineer_jpbs.json.zip)

**Comment by kalAnglin** [comment]
[Global_Airplane_Crashes_and_Fatalities_Since_1908.csv](https://github.com/N8sGit/ai_project_group_8/files/15242043/Airplane_Crashes_and_Fatalities_Since_1908.csv)


[US_Electric_Vehicle_Population_Size_History_By_County.csv](https://github.com/N8sGit/ai_project_group_8/files/15242065/Electric_Vehicle_Population_Size_History_By_County.csv)


[US_DisasterDeclarationsSummaries.csv] 
https://www.fema.gov/openfema-data-page/disaster-declarations-summaries-v2


[Global_natural_disasters.zip]
(https://github.com/N8sGit/ai_project_group_8/files/15242084/natural_disasters.zip)


[US Food Access based on supermarket accessibility]
https://www.ers.usda.gov/data-products/food-access-research-atlas/download-the-data/


[New_York_Violent__Property__and_Firearm_Rates_By_County__Beginning_1990.csv](https://github.com/N8sGit/ai_project_group_8/files/15242551/Index__Violent__Property__and_Firearm_Rates_By_County__Beginning_1990.csv)


[Chicago_Resident_Safety_Sentiment_Scores.csv](https://github.com/N8sGit/ai_project_group_8/files/15242563/Police_Sentiment_Scores.csv)

**Comment by kalAnglin** [comment]
Safety databases

**Comment by N8sGit** [comment]
Here's even more linkedin job data, 100,000 items. I think it includes jobs from all kinds of jobs outside of tech though
https://www.kaggle.com/datasets/arshkon/linkedin-job-postings

**Comment by N8sGit** [comment]
https://www.kaggle.com/datasets/asaniczka/1-3m-linkedin-jobs-and-skills-2024 This one claims to have a million

**Comment by MxOdele** [comment]
Combined data from US Census API: https://www.census.gov/data/developers/guidance.html

**NOTE:** Data from 2010 through 2019 _only_

[combined_census_data.csv](https://github.com/N8sGit/ai_project_group_8/files/15252777/combined_census_data.csv)

**Comment by kalAnglin** [comment]
[National Employment Matrix.csv](https://github.com/N8sGit/ai_project_group_8/files/15252941/National.Employment.Matrix.csv)

Reference: https://data.bls.gov/projections/occupationProj

**Comment by kalAnglin** [comment]
[AI_Job_Threat_Index.csv](https://github.com/N8sGit/ai_project_group_8/files/15253623/AI_Job_Threat_Index.csv) 

Reference:  https://www.kaggle.com/code/unclepablo/ai-impact-on-jobs

**Comment by kalAnglin** [comment]
[Electric_Vehicle_Population_Size_History_By_County.csv](https://github.com/N8sGit/ai_project_group_8/files/15253648/Electric_Vehicle_Population_Size_History_By_County.csv)

Reference: https://catalog.data.gov/dataset/electric-vehicle-population-size-history-by-county

**Comment by MxOdele** [comment]
2022 5-year estimate data from US Census API: https://www.census.gov/data/developers/guidance.html

[2022_acs5_census_data.csv](https://github.com/N8sGit/ai_project_group_8/files/15268535/2022_acs5_census_data.csv)
